name: xinput_gamepad
description: Add support to XInput controllers.
version: 0.0.3
platforms:
  windows:

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  win32: ^2.4.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
