name: console_virual_cursor
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  xinput_gamepad:
    path: "../.."

dev_dependencies:
  lints: ^1.0.0
